language: go
go:
  - 1.12.x
addons:
  apt:
    packages:
      - python3
script:
  - "python3 ./build.py -create-sample"
before_deploy:
  - "go version"
  - "ls -al"
  - "python3 ./build.py -build"
deploy:
  provider: releases
  api_key:
    secure: "AmSYoc+s0jHFiU56reH8JfDWi2RsyY3lpzNiJWSsOa1YKWFbXkqKkB1b8YVxp/8naQqbXt8aznD37JgFIS+t9gHcB5XGYxO4DDqwTqS6/hHNMbdNYl2QuLBlX16zKyAX/9uuSjWhR39sCCIvxTe7CeBT09g6QDDzA5MFP7rU7zgccK6VamLn7PKHB/yDIiJvzhufwaJbB9GlXL5CIxN8oTTvzlR4hQEP070eUBNF3xGh86a79Gnp5t5JcvCBqmhBXsVf6BC0DSEWWf9XqM6s/k3OMvOrTo2R2SfyZk+GLSMtvOwFdzJSnpq80vvbjsNXB65aGfGzb1i5mYX7PNaPKVoz4bAxpFu3vHvzdpC2YEojTluD8l2dCCc1nXYkbfJYBDHsrCyyLXdED85XvMDjmPyk/Yf56UKrJRHQKFlaS3yV0OutUrcLGx0cdM72y5a5NslQXVJ2ApCxwnWxa9H65STbXKjkXNUuVwxtYoTMazk7WgIwa0I00aMakJJGec7jxX8vx3K/H6jH1LbbaEBe9P/G8khaaCVmMrlNHeP5CB8jvZ0ujlC2zesQ58ypkYAuigcUPJomeqTVJThGUKRANAFkEaFCBimxWcjcM7qTQrS2YxWqnhovP2A1s3qmvuEgkI9OSeZeFtT4foCemHgDzDD59evcfWW6bgi+PVzgGy0="
  file:
    - overture-darwin-amd64.zip
    - overture-linux-386.zip
    - overture-linux-amd64.zip
    - overture-linux-arm.zip
    - overture-linux-arm64.zip
    - overture-linux-mips-softfloat.zip
    - overture-linux-mips-hardfloat.zip
    - overture-linux-mipsle-softfloat.zip
    - overture-linux-mipsle-hardfloat.zip
    - overture-linux-mips64.zip
    - overture-linux-mips64le.zip
    - overture-freebsd-386.zip
    - overture-freebsd-amd64.zip
    - overture-windows-386.zip
    - overture-windows-amd64.zip
  skip_cleanup: true
  on:
    tags: true
