language: go
go:
  - 1.12.x
addons:
  apt:
    packages:
      - python3
script:
  - "python3 ./build.py -create-sample"
before_deploy:
  - "go version"
  - "ls -al"
  - "python3 ./build.py -build"
deploy:
  provider: releases
  api_key: 
    secure: "mgmPnYcGDb+Yx6xp+GD9AjaJ0+mR66Wm8ojX508dU/F1Si8ZsUxvvD++EqetodOPGmu+Rz6Ms8EWOi4+EBe32I0Ubiv3m9J1Pu6F7Zt3PZpmttjMA3APph7MuBpRugecINOeZbxEjgwBQ0YDXCt0sFLrU5KlpEQLkSFzp3IMAEA4MxsC5C/CH7I+dorxSMmIqlopbn5nRkTZB3ppyl46ts5ZYmxWugG5HHLBpVe7nbeeHKp84o6/gqXwzBhUjYA7ICA4B5Z+MfN0yghL8QliiOHwpqlui1eb6zjFpkWABxq3ABPjF1DqLw9U2dzK9NZuVOvM9pCOkVzMhbIHR2yWSU0NIpDoiqKL+zeDTPPNO3xo6EspfMmWgZKwxhtKt/afkvV27ACXF/Z6mpCrSHzfQmhXYkNQk9Lch4sW7RBhT8QEP0D3BhJyhi66gndJ3+ALh1Za2G0SfnlGVqNvrk4+mhMFvlEXPv8cWtQapsbwkA4QzpBPQ5a86jliN8ZLo//853/ZO/4KoumXi1Z+8Y/oyU9gnUvLZp0Tx7GZ/zyWBDRtQcPIz0hVS3KvvEGiRqzE9YLwUFxq3lBPMiQIcfA0NR6xCbqAEKVTD+JEGlJc3fVHx/lYz5DwF/XeXuXUJn6jtp5DautBqJIFcVbHa3EaaRA67wNASVqdsvG7GtUxArg="
  file:
    - overture-darwin-amd64.zip
    - overture-linux-386.zip
    - overture-linux-amd64.zip
    - overture-linux-arm.zip
    - overture-linux-arm64.zip
    - overture-linux-mips-softfloat.zip
    - overture-linux-mips-hardfloat.zip
    - overture-linux-mipsle-softfloat.zip
    - overture-linux-mipsle-hardfloat.zip
    - overture-linux-mips64.zip
    - overture-linux-mips64le.zip
    - overture-freebsd-386.zip
    - overture-freebsd-amd64.zip
    - overture-windows-386.zip
    - overture-windows-amd64.zip
  skip_cleanup: true
  on:
    tags: true
